*AlgoGenetiques
initializeCities
	cities := Dictionary new.
"	cities at: 'Santiago' put: -33.4500 @ -70.66.
	cities at: 'Vina del Mar' put: -33 @ -71.52.
	cities at: 'New York City' put: 40.67 @ -73.94.
	cities at: 'Washington, D.C.' put: 38.89 @ -77.03."
	cities at: 'Paris' put: 48.85 @ 2.35.
	cities at: 'Nice' put: 43.70 @ 7.26.
	cities at: 'Bordeaux' put: 44.84 @ -0.58.
	cities at: 'Brest' put: 48.383 @ -4.500.
	cities at: 'Nancy' put: 48.69 @ 6.18.
	cities at: 'Toulouse' put: 43.60 @1.44.
	cities at: 'St-Brieuc' put: 48.517 @ -2.750.
	cities at: 'Vannes' put: 47.66 @ -2.733.
	cities at: 'Lille' put: 50.62 @ 3.05.
	cities at: 'Rennes' put: 48.100 @ -1.667.
	cities at: 'Cherbourg' put: 49.633 @ -1.617.
	cities at: 'Nantes' put: 47.233 @ -1.583.
	cities at: 'Marseille' put: 43.29 @ 5.36.
	cities at: 'Bayonne' put: 43.500 @ -1.467.
	cities at: 'Lyon' put: 45.76 @ 4.83.
	cities at: 'Strasbourg' put: 48.57 @ 7.75.
	cities at: 'Laval' put: 48.067 @ -0.750.

	^cities
"	cities at: 'Bogota' put: 4.5981 @ -74.07.
	cities at: 'Buenos Aires' put: -34.60 @ -58.38.
	cities at: 'Brasilia' put: -15.79 @ -47.86.
	cities at: 'Sao Paulo' put: -23.55 @ -46.63.
	cities at: 'Montevideo' put: -34.88 @ -56.18.
	cities at: 'Lima' put: -12.04 @ -77.03.
	cities at: 'La Paz' put: -16.5 @ -68.15.
	cities at: 'Quito' put: -0.25 @ -78.58.
	cities at: 'Caracas' put: 10.5 @ -66.92.
	cities at: 'Shanghai' put: 31.2 @ 121.5"